name: GitHub Actions Validator
on:
  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
         repository: Fiserv/Test-repo
      - name: List files in the repository
        run: |
         pwd
         ls -la
      - run: echo "ğŸ’¡ The Fiserv/Test-repo repository has been cloned to the runner."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
         repository: ${{ github.repository }}
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
         pwd
         ls -la
      - name: Running Validator.....
        run: |
          pwd
          cd validator
          ls -la
          npmv=$(npm --version)
          echo "NPM version installed : " $npmv
          nodev=$(node --version)
          echo "Node version installed : " $nodev
          npm install
          echo " Repo: ${{ github.repository }}"
          echo " Space: ${{ github.workspace }}"
          result=$(npm test ${{github.workspace }})
          echo "Test Results: \n"$result
          if [[ $result == *'VALIDATOR FAILED'* ]] ;then
          echo "Validator failed and exiting the Job..."
          exit 1
          elif [[ $result == *'PASSED'* ]] ;then
          echo "Validator Ran Successfully....ğŸ"
          fi
      - run: echo "ğŸ This job's status is ${{ job.status }}."
